WITH YEARLY_MAX AS
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (y.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA e
JOIN YEARLY_MAX y ON YEAR(DIFFERENTIATION_DATE) = y.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;