WITH SUM_SCORE AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM 
        HR_GRADE 
    WHERE
        YEAR = 2022
    GROUP BY 
        EMP_NO
),
MAX_SCORE AS(
    SELECT
        MAX(SCORE) AS MAX_SCORE
    FROM SUM_SCORE
)

SELECT 
    S.SCORE, 
    E.EMP_NO, 
    E.EMP_NAME, 
    E.POSITION, 
    E.EMAIL
FROM 
    SUM_SCORE AS S  
JOIN 
    HR_EMPLOYEES AS E
    ON S.EMP_NO = E.EMP_NO
JOIN
    MAX_SCORE AS M
    ON S.SCORE = M.MAX_SCORE;
    